version: "3.9"

services:
  redis:
    image: redis
    restart: always
  webapp:
    restart: always
    build:
      context: ./drfsite
#      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: ["python3", "./manage.py", "runserver", "0.0.0.0:8000"]