# Generated by Django 4.0.3 on 2022-03-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfservice', '0003_client_mailing_message_delete_bookname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
