# Generated by Django 4.0.3 on 2022-03-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfservice', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drfservice.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drfservice.mailing'),
        ),
    ]
