# Generated by Django 4.0.3 on 2022-03-30 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfservice', '0006_alter_mailing_end_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^7\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date_and_time',
            field=models.DateTimeField(),
        ),
    ]
